type User {
  username: String!
  email: String
  password: String!
  firstName: String!
  lastName: String!
}

input Auth {
  usernameOrEmail: String!
  password: String!
}

type Query{
  helloWorld:String!
}

type Mutation {
  login(auth: Auth!): String!
}
