type User {
  _id:String!
  username: String!
  email: String
  password: String!
  firstName: String!
  lastName: String!
}

input CreateUser {
  username: String!
  email: String
  password: String!
  firstName: String!
  lastName: String!
}

input Auth {
  usernameOrEmail: String!
  password: String!
}

type Query {
  helloWorld: String!
}

type Mutation {
  register(user: CreateUser!): User!
  login(auth: Auth!): String!
}
